permissions:
  contents: read
name: main-workflow

on:
  push:
    branches: [ main, develop, 'sprint/**', 'release/**' ]
  pull_request:
    branches: [ main, develop, 'sprint/**', 'release/**' ]

jobs:
  trigger-L1:
    if: false  # Disabled
    uses: ./.github/workflows/L1-tests.yml
    with:
      caller_source: local
    secrets:
      RDKCM_RDKE: ${{ secrets.RDKCM_RDKE }}

  trigger-L2:
    if: false  # Disabled
    uses: ./.github/workflows/L2-tests.yml
    with:
      caller_source: local
    secrets:
      RDKCM_RDKE: ${{ secrets.RDKCM_RDKE }}

  trigger-L2-OOP:
    if: false  # Disabled
    uses: ./.github/workflows/L2-tests-oop.yml
    with:
      caller_source: local
    secrets:
      RDKCM_RDKE: ${{ secrets.RDKCM_RDKE }}
